// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitmentAuth.Infrastructure.Persistence;

#nullable disable

namespace RecruitmentAuth.Infrastructure.Migrations
{
    [DbContext(typeof(RecruitmentAuthContext))]
    partial class RecruitmentAuthContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.AuditLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp(3)");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("event");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Metadata")
                        .HasColumnType("longtext")
                        .HasColumnName("metadata");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserId")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CreatedAt" }, "audit_logs_created_at_idx");

                    b.HasIndex(new[] { "Event" }, "audit_logs_event_idx");

                    b.HasIndex(new[] { "UserId" }, "audit_logs_user_id_idx");

                    b.ToTable("audit_logs", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp(3)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("token_hash");

                    b.Property<bool>("Used")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("used");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TokenHash" }, "email_verification_tokens_token_hash_idx")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "email_verification_tokens_user_id_idx");

                    b.ToTable("email_verification_tokens", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.LoginAttempt", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("success");

                    b.Property<string>("UserId")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CreatedAt" }, "login_attempts_created_at_idx");

                    b.HasIndex(new[] { "Email", "IpAddress" }, "login_attempts_email_ip_address_idx");

                    b.HasIndex(new[] { "UserId" }, "login_attempts_user_id_idx");

                    b.ToTable("login_attempts", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp(3)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("token_hash");

                    b.Property<bool>("Used")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("used");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TokenHash" }, "password_reset_tokens_token_hash_idx")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "password_reset_tokens_user_id_idx");

                    b.ToTable("password_reset_tokens", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.Question", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<string>("ExpectedOutput")
                        .HasColumnType("text")
                        .HasColumnName("expected_output");

                    b.Property<string>("Options")
                        .HasColumnType("json")
                        .HasColumnName("options");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.Property<string>("TestId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("test_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TestId" }, "questions_test_id_idx");

                    b.ToTable("questions", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.QuestionAnswer", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("AnswerText")
                        .HasColumnType("text")
                        .HasColumnName("answer_text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_correct");

                    b.Property<decimal?>("PointsAwarded")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("points_awarded");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("question_id");

                    b.Property<string>("SelectedOptions")
                        .HasColumnType("json")
                        .HasColumnName("selected_options");

                    b.Property<string>("SubmissionId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("submission_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("QuestionId");

                    b.HasIndex(new[] { "SubmissionId", "QuestionId" }, "question_answers_sub_question_unique")
                        .IsUnique();

                    b.ToTable("question_answers", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp(3)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("expires_at");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("family");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("Revoked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("revoked");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Family" }, "refresh_tokens_family_idx");

                    b.HasIndex(new[] { "Revoked" }, "refresh_tokens_revoked_idx");

                    b.HasIndex(new[] { "TokenHash" }, "refresh_tokens_token_hash_idx")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "refresh_tokens_user_id_idx");

                    b.ToTable("refresh_tokens", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.Test", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("RecruiterId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("recruiter_id");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RecruiterId" }, "tests_recruiter_id_idx");

                    b.ToTable("tests", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.TestSubmission", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("candidate_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("MaxScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("max_score");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("score");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("submitted_at");

                    b.Property<string>("TestId")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("test_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CandidateId" }, "test_submissions_candidate_id_idx");

                    b.HasIndex(new[] { "TestId", "CandidateId" }, "test_submissions_test_candidate_unique")
                        .IsUnique();

                    b.ToTable("test_submissions", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("current_timestamp(3)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("GithubId")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("github_id");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("google_id");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_email_verified");

                    b.Property<bool>("IsTwoFactorEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_two_factor_enabled");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("LinkedinId")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("linkedin_id");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('CANDIDATE','RECRUITER','ADMIN')")
                        .HasColumnName("role")
                        .HasDefaultValueSql("'CANDIDATE'");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('PENDING_VERIFICATION','ACTIVE','SUSPENDED','DELETED')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'PENDING_VERIFICATION'");

                    b.Property<string>("TwoFactorSecret")
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("two_factor_secret");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(3)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "users_email_idx")
                        .IsUnique();

                    b.HasIndex(new[] { "GithubId" }, "users_github_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "GoogleId" }, "users_google_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "LinkedinId" }, "users_linkedin_id_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "users_phone_idx")
                        .IsUnique();

                    b.HasIndex(new[] { "Status" }, "users_status_idx");

                    b.ToTable("users", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_unicode_ci");
                });

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("RecruitmentAuth.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("audit_logs_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.EmailVerificationToken", b =>
                {
                    b.HasOne("RecruitmentAuth.Domain.Entities.User", "User")
                        .WithMany("EmailVerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("email_verification_tokens_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.LoginAttempt", b =>
                {
                    b.HasOne("RecruitmentAuth.Domain.Entities.User", "User")
                        .WithMany("LoginAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("login_attempts_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("RecruitmentAuth.Domain.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("password_reset_tokens_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.Question", b =>
                {
                    b.HasOne("RecruitmentAuth.Domain.Entities.Test", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("questions_test_id_fkey");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.QuestionAnswer", b =>
                {
                    b.HasOne("RecruitmentAuth.Domain.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("question_answers_question_id_fkey");

                    b.HasOne("RecruitmentAuth.Domain.Entities.TestSubmission", "Submission")
                        .WithMany("Answers")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("question_answers_submission_id_fkey");

                    b.Navigation("Question");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("RecruitmentAuth.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("refresh_tokens_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.Test", b =>
                {
                    b.HasOne("RecruitmentAuth.Domain.Entities.User", "Recruiter")
                        .WithMany("CreatedTests")
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tests_recruiter_id_fkey");

                    b.Navigation("Recruiter");
                });

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.TestSubmission", b =>
                {
                    b.HasOne("RecruitmentAuth.Domain.Entities.User", "Candidate")
                        .WithMany("Submissions")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("test_submissions_candidate_id_fkey");

                    b.HasOne("RecruitmentAuth.Domain.Entities.Test", "Test")
                        .WithMany("Submissions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("test_submissions_test_id_fkey");

                    b.Navigation("Candidate");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.Test", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.TestSubmission", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("RecruitmentAuth.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedTests");

                    b.Navigation("EmailVerificationTokens");

                    b.Navigation("LoginAttempts");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
