-- AlterEnum: Add PENDING_APPROVAL to UserStatus
-- MySQL ENUM must be redefined with all values
ALTER TABLE `users` MODIFY COLUMN `status` ENUM('PENDING_VERIFICATION', 'PENDING_APPROVAL', 'ACTIVE', 'SUSPENDED', 'DELETED') NOT NULL DEFAULT 'PENDING_VERIFICATION';
