namespace RecruitmentAuth.Domain.Enums;

public enum TestCategory
{
    CODING_PROGRAMMING,
    DATA_STRUCTURES_ALGORITHMS,
    DEBUGGING,
    SYSTEM_DESIGN,
    DATABASE_SQL,
    OOP,
    FRAMEWORK_TECHNOLOGY,
    API_DEVELOPMENT,
    CLOUD_DEVOPS,
    VERSION_CONTROL,
    TESTING_QA,
    SECURITY,
    PERFORMANCE_OPTIMIZATION,
    CODE_REVIEW,
    PROJECT_BASED,
    TECHNICAL_QUIZ,
    PROBLEM_SOLVING_LOGIC,
    COMMUNICATION_COLLABORATION
}
